apiVersion: v1
kind: Service
metadata:
  name: spark-driver-service
spec:
  selector:
    notebook-instance-name: kubeflow-poc
  ports:
    - name: driver-port
      port: 8989
      targetPort: 8989
  clusterIP: None
  type: ClusterIP
