apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: spark
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: awsebscsiprovisioner
---
apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: spark-notebook
  namespace: spark
  labels:
    notebook-instance-name: kubeflow-poc
spec:
  template:
    spec:
      containers:
      - env: []
        image: akirillov/jupyter:kubeflow-spark-horovod
        name: spark-notebook
        resources:
          limits: {}
          requests:
            cpu: "5"
            memory: 4.0Gi
        volumeMounts:
          - mountPath: /home/jovyan
            name: spark-pvc
          - mountPath: /dev/shm
            name: dshm
        ports:
          - containerPort: 8888
            name: notebook-port
            protocol: TCP
      serviceAccountName: spark-sa
      ttlSecondsAfterFinished: 300
      volumes:
        - name: spark-pvc
          persistentVolumeClaim:
            claimName: spark-pvc
        - emptyDir:
            medium: Memory
          name: dshm
